services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: cd backend-chat-app && npm install && npm run build
    startCommand: cd backend-chat-app && npm start
    envVars:
      - key: NODE_ENV
        value: production

